Configuration:
  Spawners:
    DisableCommandSaving: false
  RandomSpawning:
    DisableVanillaSpawns: false
    GenerateSpawnPoints: false
    SpawnRadiusPerPlayer: 64
    SpawnRadiusPerPlayerMin: 18
    SpawnRadiusPerPlayerY: 16
    PlayerClusterDistance: 24.0
    LimitMultiplier: 1.1
    LocalGroupMultiplier: 0.12
    SpawningLimit: -1
    LocalSpawningLimit: 36
    IgnoreVanillaMobs: false
    IgnoreUnnaturalMobs: false
    ReplaceObeysCap: false
    SharedCooldown: true
    MaxGenerationAttempts: 9
    Generator: NONE
    MaxGenerationTime: 5
